### ISSUE TITLE
Hydrate abstract class

### ISSUE THREAD

**Issue by Noles** [Maks3w/FR3DLdapBundle#96]
In my opinion the trait in the AbstractHydrator class produces only overhead. The trait will be only used by the abstract class and the Hydrator classes always extends the abstract. So why do we need this?

**Comment by Noles** [comment]
In addition why is the createUser() abstract defined in the abstract class if we have an interface. I think in this case it would be more clear to define the methods abstract in the interface. What do you mean?

**Comment by Maks3w** [comment]
The trait can be used without the abstract. I opt for to use the trait because I'm feel a bit proud of develop that fragment of code which allow quick configuration just tunning the config.yml

AbstractClass is more like a quick prototipe for to create custom hydrators, probably the class name is to generic and should be named to something like AbstractQuickHydratorImplementation

`createUser` does not fit with the purpose of the interface in any way so it's not expected use Hydrator classes for to create empty user instances.

I take note of your concerns but I preffer to have more feedback before to change the classes (again).

**Comment by Noles** [comment]
Sure the trait can be used without the abstract but will this really happen. I think most of the time the abstract class would be used for custom hydrators because its there and the predefined hydrators extend this. 

If the AbstractClass should be more like a prototype then why is this class extended by the legacyHydrator? In this case it should be standalone, use the trait and only implement the interface. 

Currently the two way's are more or less combined.
For me it's a little confusing and not really clear what should be set where but maybe that's me own feeling.
